### PR TITLE
Use Ubuntu for s390x

### PR DESCRIPTION
**Pull request by nealef**
####  Use Ubuntu for s390x

* build-files/build-image.sh
   - Common build script

* build-files/build-image.sh-ppc64le
   build-files/build-image.sh-s390x
   - Delete and use single build script

* distro/almalinux.yaml.tmpl
   - No need to create LXD base container for almalinux

* setup-build-env.sh
   - Use same build script and LXD container

#### Make build work as non-root

* build-files/build-image.sh
   - When building as a github action the build runs under a non-root user so the use of sudo is required.
   - Change creating /etc/rc.local directly to having it copied in by setup (otherwise EPERM)

 * build-files/rc.local
    - When building under podman a `setcap` of the ping command is required

 * setup-build-env.sh
    - Copy build-files/rc.local to the container's /etc/rc.local
    - Invoke the build script under a non-root user

### CODE REVIEW

**Comment by anup-kodlekere** [comment]
LGTM! 
As we move from TravisCI to GitHub Actions to build gaplib, we will need to have at least 1 runner listening to the prod rabbitmq queues or we won't be able to build it in CI with a single github app. Just a heads up!

**Comment by nealef** [comment]
I also find that sometimes RabbitMQ isn’t all the way up before gh_app gets up and so fails. I did change the order of the startup and that seemed to help but it’s not perfect. Depending on how complex the MQ stuff is we might want to looks at ZeroMQ.

**Comment by anup-kodlekere** [comment]
Okay. I'm not that familiar with ZMQ but upon a cursory reading of the docs, it seems to use a P2P model against the centralized-queueing of RabbitMQ? I think that will change the model of our "job-queueing" modules and require lot of rework? Thoughts?

**Comment by nealef** [comment]
It operates in multiple modes P2P, Subscriber/Publisher, Router/Dealer … The patterns are described in https://zguide.zeromq.org/

How does the existing mechanism work?

**Comment by anup-kodlekere** [comment]
We use Pub/Sub

**Comment by nealef** [comment]
Chapters 2 and 5 of https://zguide.zeromq.org/

**Pull request merged**
