### PR TITLE
Fix patch failure for runner

### PR DESCRIPTION
**Pull request by shahidhs-ibm**
**Issue:**
Getting below error while applying patch for runner
```
$ git apply ../runner-ppc64le.patch
error: patch failed: src/global.json:1
error: src/global.json: patch does not apply
```

**Fix:**
The change fixes the issue. Also executed tests with `$ ./dev.sh test` on runner's main branch after applying the patch. No test failures observed (tested on `d7777fd6320d7c372447d44c4182258aa5afd3f9` commit on the main branch of runner repo).
```
  Test run for /home/ubuntu/RUNNER/runner/src/Test/bin/Debug/net7.0/Test.dll (.NETCoreApp,Version=v7.0)
  Microsoft (R) Test Execution Command Line Tool Version 17.4.1+79d56b02b69a582cd90428878a5e9411ab7538f5 (ppc64le)
  Copyright (c) Microsoft Corporation.  All rights reserved.

  Starting test execution, please wait...
  A total of 1 test files matched the specified pattern.
  Results File: /home/ubuntu/RUNNER/runner/src/Test/TestResults/_a37ae5c79589_2024-02-28_10_21_21.trx

  Passed!  - Failed:     0, Passed:   631, Skipped:     0, Total:   631, Duration: 29 s - Test.dll (net7.0)
~/RUNNER/runner/src

```

### CODE REVIEW

**Comment by anup-kodlekere** [comment]
LGTM!
@nealef  can we get this for s390x? We don't have the machines to test this change locally.

**Comment by nealef** [comment]
Isn't this a PPC-only fix? We are using .NET 6 for the build not 7.

**Comment by anup-kodlekere** [comment]
Hmm, the Z patch will fail to apply since it's expecting the cloned repo to have `6.0.418`  in src/global.json right?

**Comment by nealef** [comment]
Ah, I see what you mean.

**Comment by nealef** [comment]
I’ve removed my fix to the file altogether. It’s no longer needed.

From: Anup Kodlekere ***@***.***>
Date: Thursday, February 29, 2024 at 21:39
To: anup-kodlekere/gaplib ***@***.***>
Cc: Neale Ferguson ***@***.***>, Mention ***@***.***>
Subject: Re: [anup-kodlekere/gaplib] Fix patch failure for runner (PR #9)

Yeah, it's going to be a headache to keep these things updated. I'm looking into adding the CI stuff, so that the nightly builds can notify in-case of breakage.

**Pull request merged**
